# Generated by Django 4.0.6 on 2022-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=100)),
                ('prix_article', models.FloatField(default=0.0)),
                ('disponible_article', models.BooleanField(default=True)),
                ('quantite_en_stock', models.IntegerField(default=0)),
                ('memo_article', models.TextField(blank=True, max_length=500)),
                ('image_article', models.ImageField(blank=True, null=True, upload_to='dir_image_article')),
            ],
        ),
    ]
